### ISSUE TITLE
table without any footer having last row treated like footer

### ISSUE THREAD

**Issue by feanor07** [Jo-Geek/jQuery-FixTableHeader#10]
I have created a table without any footer and used your plugin; the plugin just seems to be treating the last row as if it is a footer even if it is not within any `<tfoot>` tag. It should be great if it just ignores footer treatment in case table does not have a footer. 

What I mean is the last row is being assigned `fth-footer` class regardless of whether or not it is within a footer tag.

**Comment by Jo-Geek** [comment]
Can you please share your html code and the way you have called this plugin ?
