### ISSUE TITLE
Scrolled Data are hiding behind the fixedHeadear , on hovering table header the scrolled data is getting displayed.ho to hide it?

### ISSUE THREAD

**Issue by kraravind167** [Jo-Geek/jQuery-FixTableHeader#11]

**Comment by Jo-Geek** [comment]
I could not recreate this issue. Can you post a snippet or a fiddle so that I can check?

**Comment by kraravind167** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/18467253/69138432-ac6f0680-0ae4-11ea-9233-07951de7cf9c.png)

After Scrolling if i hover on thead , the scrolled tbody cells are getting displayed

`<div id="fixHeadFoot" class="scrolltest">
                    <table class="table table-striped" style="text-align: center;overflow-y:auto;">
                        <thead>
                            <tr style="background: #036266;color: #FFF;">
                                <th >Employee Code</th>
                                <th >Employee Name</th>
                                <th>Designation</th>
                            </tr>
                        </thead>
                        <tbody id="tblEmployeeDetails" style=""></tbody>
                    </table>
                </div>`

`.scrolltest {
        height: 450px;
        width: 100%;
        overflow: auto;
    }
    td.fth-header, th.fth-header,
    td.fth-footer, th.fth-footer {
        border-top: none !important;
        border-bottom: 1px solid #ddd;
    }
    td.fth-header, th.fth-header {
        background-color: #036266;
        color: white;
    }
    td.fth-footer, th.fth-footer {
        background-color: #036266;
        color: white;
    }        
`

`$('#fixHeadFoot').fixTableHeader();`

**Comment by kraravind167** [comment]
i've also mailed to your  hotmail

**Comment by Jo-Geek** [comment]
Tried your code. check this out [https://jsfiddle.net/fpnqmr09/1/](https://jsfiddle.net/fpnqmr09/1/)
Seems to be working fine.

Also do not apply background color to the `thead` apply it to each each `th` inside the `thead`

Check your mail too

**Comment by kraravind167** [comment]
Let me check

**Comment by Jo-Geek** [comment]
Hope I have resolved your issue
